### ISSUE TITLE
Gradle Plugins Issue

### ISSUE THREAD

**Issue by pvegh** [remal/coupon-clipper#47]
Sorry for hijacking this project for reporting this. Didn't find a better place..

name.remal.check-dependency-updates
from
https://plugins.gradle.org/plugin/name.remal.gradle-plugins
doesn't support gradle configuration cache, which means it fails on the project when this new feature is used.

**Comment by remal** [comment]
@pvegh sorry, but `name.remal.check-dependency-updates` plugin is not supported anymore. I suggest using tools like [Renovate](https://renovatebot.com/) or [Dependabot](https://docs.github.com/en/code-security/dependabot) to handle dependency changes.
